"""initial schema

Revision ID: 5a3d1b0a36f9
Revises:
Create Date: 2026-09-17 21:44:51.692091

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5a3d1b0a36f9"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("subject", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("status IN ('ACTIVE', 'DISABLED')", name="ck_users_status"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider", "subject", name="uq_users_provider_subject"),
    )
    op.create_table(
        "asset_config",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("asset", sa.String(length=16), nullable=False),
        sa.Column("pair", sa.String(length=32), nullable=False),
        sa.Column("target_pct", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("target_pct >= 0 AND target_pct <= 100", name="ck_asset_config_target_pct"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "asset"),
    )
    op.create_table(
        "orders",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("cl_ord_id", sa.String(length=64), nullable=False),
        sa.Column("txid", sa.String(length=64), nullable=True),
        sa.Column("pair", sa.String(length=32), nullable=False),
        sa.Column("asset", sa.String(length=16), nullable=False),
        sa.Column("side", sa.String(length=8), nullable=False),
        sa.Column("reason", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("requested_fiat", sa.Numeric(precision=24, scale=12), nullable=False),
        sa.Column("executed_volume", sa.Numeric(precision=24, scale=12), nullable=True),
        sa.Column("executed_price", sa.Numeric(precision=24, scale=12), nullable=True),
        sa.Column("fee", sa.Numeric(precision=24, scale=12), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("reason IN ('INVEST', 'REBALANCE')", name="ck_orders_reason"),
        sa.CheckConstraint("side IN ('buy', 'sell')", name="ck_orders_side"),
        sa.CheckConstraint("status IN ('PENDING', 'FILLED', 'FAILED')", name="ck_orders_status"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cl_ord_id"),
    )
    op.create_index("ix_orders_user_created_at", "orders", ["user_id", "created_at"], unique=False)
    op.create_index(
        "ix_orders_user_pending",
        "orders",
        ["user_id"],
        unique=False,
        postgresql_where=sa.text("status = 'PENDING'"),
    )
    op.create_table(
        "portfolio_snapshots",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("as_of", sa.DateTime(timezone=True), nullable=False),
        sa.Column("fiat", sa.String(length=8), nullable=False),
        sa.Column("total_value", sa.Numeric(precision=24, scale=12), nullable=False),
        sa.Column("cash", sa.Numeric(precision=24, scale=12), nullable=False),
        sa.Column("holdings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_portfolio_snapshots_user_as_of", "portfolio_snapshots", ["user_id", "as_of"], unique=False
    )
    op.create_table(
        "proposal",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("plan", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("trigger", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "status IN ('EXECUTING', 'EXECUTED', 'LIVE', 'WITHDRAWN')", name="ck_proposal_status"
        ),
        sa.CheckConstraint("trigger IN ('MANUAL', 'SCHEDULED')", name="ck_proposal_trigger"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("log_messages", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_sessions_started_at", "sessions", ["started_at"], unique=False)
    op.create_index("ix_sessions_user_started_at", "sessions", ["user_id", "started_at"], unique=False)
    op.create_table(
        "user_credentials",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("ciphertext", sa.LargeBinary(), nullable=False),
        sa.Column("nonce", sa.LargeBinary(), nullable=False),
        sa.Column("key_version", sa.Integer(), nullable=False),
        sa.Column("validated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "user_settings",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("fiat", sa.String(length=8), nullable=False),
        sa.Column("invest_cash_enabled", sa.Boolean(), nullable=False),
        sa.Column("cash_rebalance_enabled", sa.Boolean(), nullable=False),
        sa.Column("auto_rebalance_enabled", sa.Boolean(), nullable=False),
        sa.Column("min_drift_pct", sa.Numeric(precision=4, scale=1), nullable=False),
        sa.Column("min_order_fiat", sa.Numeric(precision=10, scale=1), nullable=False),
        sa.Column("invest_cadence_mode", sa.String(length=16), nullable=False),
        sa.Column("invest_interval_days", sa.Integer(), nullable=True),
        sa.Column("invest_interval_months", sa.Integer(), nullable=True),
        sa.Column("invest_cadence_anchor", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rebalance_cadence_mode", sa.String(length=16), nullable=False),
        sa.Column("rebalance_interval_days", sa.Integer(), nullable=True),
        sa.Column("rebalance_interval_months", sa.Integer(), nullable=True),
        sa.Column("rebalance_cadence_anchor", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_invest_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_rebalance_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("paused", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "invest_cadence_mode IN ('MIN', 'INTERVAL')", name="ck_user_settings_invest_cadence_mode"
        ),
        sa.CheckConstraint(
            "rebalance_cadence_mode IN ('MIN', 'INTERVAL')", name="ck_user_settings_rebalance_cadence_mode"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_index(
        "ix_user_settings_next_invest_at",
        "user_settings",
        ["next_invest_at"],
        unique=False,
        postgresql_where=sa.text("paused = false"),
    )
    op.create_index(
        "ix_user_settings_next_rebalance_at",
        "user_settings",
        ["next_rebalance_at"],
        unique=False,
        postgresql_where=sa.text("paused = false"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_user_settings_next_rebalance_at",
        table_name="user_settings",
        postgresql_where=sa.text("paused = false"),
    )
    op.drop_index(
        "ix_user_settings_next_invest_at",
        table_name="user_settings",
        postgresql_where=sa.text("paused = false"),
    )
    op.drop_table("user_settings")
    op.drop_table("user_credentials")
    op.drop_index("ix_sessions_user_started_at", table_name="sessions")
    op.drop_index("ix_sessions_started_at", table_name="sessions")
    op.drop_table("sessions")
    op.drop_table("proposal")
    op.drop_index("ix_portfolio_snapshots_user_as_of", table_name="portfolio_snapshots")
    op.drop_table("portfolio_snapshots")
    op.drop_index(
        "ix_orders_user_pending", table_name="orders", postgresql_where=sa.text("status = 'PENDING'")
    )
    op.drop_index("ix_orders_user_created_at", table_name="orders")
    op.drop_table("orders")
    op.drop_table("asset_config")
    op.drop_table("users")
    # ### end Alembic commands ###
