"""order cost, error and attempt time

Revision ID: 97e34820ce16
Revises: 1f1a1f05d7e9
Create Date: 2026-10-01 17:25:12.835050

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "97e34820ce16"
down_revision: str | Sequence[str] | None = "1f1a1f05d7e9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("orders", sa.Column("cost", sa.Numeric(precision=24, scale=12), nullable=True))
    op.add_column("orders", sa.Column("error", sa.String(length=64), nullable=True))
    op.add_column(
        "orders",
        sa.Column(
            "attempted_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders", "attempted_at")
    op.drop_column("orders", "error")
    op.drop_column("orders", "cost")
    # ### end Alembic commands ###
